# Publications

::: {#list}
:::

:::::::::::::: {#refs .references .csl-bib-body .hanging-indent entry-spacing="1" line-spacing="2"}
::: {#ref-stocktonInterruptedTimeSeries2026 .csl-entry}
**Stockton, B.**, Kahn, L. G., Mehta-Lee, S. S., & Hade, E. M. (2026).
[(Submitted to *Statistical Methods in Medical Research*)]{.nocase}
Interrupted time series analysis of count data with nuisance
interruptions. In *arXiv.org*. arXiv.
<https://doi.org/10.48550/arXiv.2607.19493>
:::

::: {#ref-stocktonCommentaryResurrectingCompletecase2026 .csl-entry}
**Stockton, B.**, & Harel, O. (2026). Commentary on " *Resurrecting*
*Complete-Case Analysis: A Defense* ": The loss of information remains
unresolved. *American Journal of Epidemiology*, *195*(6), 1779--1781.
<https://doi.org/10.1093/aje/kwag068>
:::

::: {#ref-stocktonClarifyingIdentificationEstimation2025 .csl-entry}
**Stockton, B.**, Santacatterina, M., Mandal, S., Cleland, C. M., Hade, E.
M., Illenberger, N., Meropol, S., Troxel, A. B., Petkova, E., Yu, C., &
Tarpey, T. (2026). *[(Submitted to *Statistical Methods in Medical
Research*)]{.nocase} Clarifying the role of placebo response
classification in the analysis of the Sequential Parallel Comparison
Design*. *arXiv:2511.19677*. <https://doi.org/10.48550/arXiv.2511.19677>
:::

::: {#ref-stocktonInProgressCh2 .csl-entry}
**Stockton, B.**, & Harel, O. (2026). [(Accepted by the [Journal of Applied
Statistics]{.nocase})]{.nocase} [Incomplete Angular Time Series
Imputation with a Projected Normal Autoregressive Process and Exogenous
Predictors]{.nocase}. *Journal of Applied Statistics*.
:::

::: {#ref-guptaCompData2025 .csl-entry}
Gupta, S., **Stockton, B.**, & Harel, O. (2025). [Adapting Multiple
Imputation for Compositional Survey Data]{.nocase}. *American Journal of
Undergraduate Research*, *22*, 13--29.
<https://doi.org/10.33697/ajur.2025.146>
:::

::: {#ref-stocktonSubmittedSDL .csl-entry}
**Stockton, B.**, Gupta, S., Harel, O., & Sinharay, S. (Ed.). (2025). *[Data
Confidentiality, Differential Privacy, and Statistical Disclosure
Control.]{.nocase} [Encyclopedia of Social Measurement]{.nocase}* (2nd
Edition). Elsevier.
:::

::: {#ref-stocktonInProgressCh13 .csl-entry}
**Stockton, B.**, & Harel, O. (2025). *(In Progress) [Multiple Imputation
for Analyzing Spatial Data with Incomplete Angular
Predictors]{.nocase}*.
:::

::: {#ref-stocktonInProgressCountITS .csl-entry}
**Stockton, B.**, Kahn, L., Mehta-Lee, S., & Hade, E. (2025). *(In Progress)
[Assessing the Impacts of Texas's Six-Week Abortion Ban on Maternal
Morbiity Using Electronic Health Records]{.nocase}*.
:::

::: {#ref-stocktonInProgressCrim2 .csl-entry}
Strange, C. C., **Stockton, B.**, Zvonkovich, J., & Harel, O. (2025). *(In
Progress) [Multiple Imputation Using Pattern-mixture Modeling]{.nocase}
to Assess the Sensitivity of Race/Ethnicity Effect Estimates in
[Sentencing Given Non-ignorable Incomplete Data]{.nocase}*.
:::

::: {#ref-sidiNoninferiorityClinicalTrials2024 .csl-entry}
Sidi, Y., **Stockton, B.**, & Harel, O. (2024). Non-inferiority Clinical
Trials: Treating Margin as Missing Information. *The New England Journal
of Statistics in Data Science*, 1--8.
<https://doi.org/10.51387/24-NEJSDS57>
:::

::: {#ref-stocktonNowYouSee2023 .csl-entry}
**Stockton, B.**, Strange, C. C., & Harel, O. (2023). Now You See It, [Now
You Don't]{.nocase}: A Simulation and Illustration of the Importance of
Treating Incomplete Data in Estimating Race Effects in Sentencing.
*Journal of Quantitative Criminology*, *40*, 563--590.
<https://doi.org/10.1007/s10940-023-09577-w>
:::
::::::::::::::
